sudo: enabled
language: c

matrix:
  include:
  - os: linux
    arch: amd64
    dist: focal
    env:
      - CONFIGURATION=linux/amd64

  - os: linux-ppc64le
    arch: ppc64le
    dist: focal
    env:
      - CONFIGURATION=linux/ppc64le

  - os: linux
    arch: arm64
    dist: bionic
    env:
      - CONFIGURATION=linux/arm64

before_script:
  - sudo ./scripts/xrtdeps.sh
  - cd src

before_install:
  - sudo apt-get update

script:
  - make all
